### ISSUE TITLE
Alpine 3.18 and 3.19 are missing

### ISSUE THREAD

**Issue by yarons** [chef/os_release#29]
# Describe the problem
The list contains former versions of alpine but not the most recent ones.

## Possible Solution
Add them

**Comment by kmf** [comment]
@yarons hope it gets merged

**Comment by kmf** [comment]
cc @Stromweld

**Comment by yarons** [comment]
I was thinking about a simple script that will pull those files directly from docker images (either with `docker cp` or attaching a volume etc.)
Are there any discussions about this? Is it good enough?

**Comment by kmf** [comment]
@yarons I think it can work :)

**Comment by Stromweld** [comment]
sorry I missed this till now. update merged.
